version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - ./model:/app/model
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
      - ./model:/app/model
    env_file:
      - .env

  redis:
    build: ./redis
    ports:
      - "6379:6379"
