[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#E0E4EF"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
